### PR TITLE
Stable

### PR DESCRIPTION
**Pull request by 912d**
Added feature showing user default popup window to select location of ffmpeg file

### CODE REVIEW

**Comment by Open96** [comment]
I like it and I always felt that this particular box needed that. 

The only thing that I think you should have done was to relay on SettingsManager's getFileManagerCommand() method and open window via Runtime.exec(). I'm not saying FileChooser is bad (probably actually better than my implementation), but all file chooser operations in this application are done that way and I would like to keep it the same across application.

Let me know if you want to make those changes or leave it up to me and I will merge your PR.

**Comment by 912d** [comment]
Sure thing, I'll rewrite it to match your applications style.

**Comment by 912d** [comment]
I have tried to implement it in a way you described. I couldn't make it work properly, mainly because Runtime.exec () is opening usual explorer.exe window, not for selecting one file.

I could use your help as I'm unable to do it in your way.

``` 
public void showFileChooser(MouseEvent mouseEvent) throws IOException, InterruptedException {
        final String fileManagerCommand = SettingsManager.getInstance().getFileManagerCommand();
        final Process exec = Runtime.getRuntime().exec(fileManagerCommand);
        final InputStream inputStream = exec.getInputStream();

**Comment by Open96** [comment]
Nevermind, I must have not been thinking straight. Your solution with FileChooser is perfectly fine and I thought about something else when I wanted to make you use Runtime.exec() for some reason. Sorry for wasting your time on that...

**Pull request merged**
